### ISSUE TITLE
Request: Integration with Action Center

### ISSUE THREAD

**Issue by gimjun** [BobVul/GrowlToToast#1]
Hey man, thanks for making this Display for Growl-for-Windows.
It was super easy to install - just pasted the unzipped folder into the Displays folder of Growl, set it as default, and I was up and running!

Would it be possible to integrate the notifications into Action Center?
(So that, once they slide out of screen, if I miss the notification it'll be waiting for my attention in the Action Center!)

Thanks for your time and effort, and for putting this out for free!

**Comment by BobVul** [comment]
Thanks for bringing this up.

I did a bit of digging, and, [as it turns out](http://stackoverflow.com/a/34072291/1030702), the [process](http://blogs.msdn.com/b/tiles_and_toasts/archive/2015/10/16/quickstart-handling-toast-activations-from-win32-apps-in-windows-10.aspx) for getting notifications to persist from a desktop program is quite complex.

It's a little confusing though - the documentation suggests that notifications should automatically persist even without an "activation"/"action" (click on notification to do something), but in practice this does not seem to be the case - at least with what you've noticed and what other people with other programs experienced.

I will try to get something up when I have time, though it might take a while.

**Comment by gimjun** [comment]
Thank you for such a quick reply and for looking into what seems like a terribly complicated task!

Man, I have a feeling this is probably more trouble than it's worth, so please don't spend too much time obsessing over making this work :-s

Thanks again for your kind effort, and best wishes!

**Comment by BobVul** [comment]
I finally got my hands on a Windows 10 machine.

I've tested, and the action center _does_ keep old Toaster messages: 
![screenshot](https://cloud.githubusercontent.com/assets/1674237/13905354/a8ba6e64-ef11-11e5-87ac-46ae3047b9c5.png)

However, I did actually implement support for Growl's `CloseAllOpenNotifications` and `CloseLastNotification` handlers, so it's possible (and quite likely) that Growl is sending those.

Are your Growl idle settings currently set to "Never consider me idle or away"?

If you want, I can add an option to ignore commands from Growl to close notifications.

**Comment by BobVul** [comment]
It's also possible that whatever you have sending the notifications _to_ Growl is doing this.

If you want to try the new option and see if that works for you, grab [v0.2a](https://github.com/Elusive138/GrowlToToast/releases/tag/v0.2a). Let me know how that goes.

**Comment by gimjun** [comment]
Hey man, thanks for working on this!

I tried out the new version, and it works well as before, but the notifications don't stay in the action center. While a notification is on-screen, if you open the control center, this notif will appear under the GrowlToToast section. But, if you reopen the action center, all notifs are gone :/ (without dismissing). If the notification has already slided-out, then there is no trace in action center.

And yea, I made sure to "Never consider me idle" and tested both new options in the GrowlToToast display.

I'm not sure, but I think it might have to with the fact that Growl does not register as a notifying app in windows settings>notifications.If it were, then you can go into its additional settings where you can select whether you want a sound, silently go to action center without slide-in alert, or disable notifications entirely.

I don't know if this is a brick wall :-s but again thank you so much for working on this!

There are some non-essential notifications for which this display is just perfect, e.g. every time winamp changes song, i see this little native windows slider come in, and it looks Awesome!

**Comment by Elusive138** [comment]
@g

**Comment by BobVul** [comment]
I think I might've gotten it this time. Give [v0.2a3](https://github.com/Elusive138/GrowlToToast/releases/tag/v0.2a3) a shot and let me know how it goes.

**Comment by gimjun** [comment]
This is amazing, it works!! The notifications stay in the Action Center after they slide out or are closed - great work my friend, thank you very much!
