### ISSUE TITLE
Currently does not work in 1709

### ISSUE THREAD

**Issue by BobVul** [BobVul/GrowlToToast#11]
See #8 and #9

**Comment by BobVul** [comment]
Looks like I'll have to create that shortcut. A couple of options:

* Auto-create whenever a message is generated
* Add button to create in Growl settings panel
* Make an installer that creates the shortcut and also installs the Growl files in the correct place

I'm leaning towards the button in the settings panel as the easiest solution. An installer would make the install process easier, but is quite a bit harder to manage (especially since Growl plugins seem to be a per-user thing, not a per-machine thing?).

**Comment by BobVul** [comment]
> I've just reinstalled the new version, and can confirm that the latest version of Android notifier works with Growl's other displays but not with GtT

@trentyarwood When you say reinstalled - did it happen to work before reinstalling? i.e. an existing GtT installation that was upgraded from 1703 to 1709?

**Comment by trentyarwood** [comment]
Sorry, no.

I reinstalled win 10 a while ago and only just got around to setting up growl again.

**Comment by BobVul** [comment]
Looks like I forgot to block the update on my dev machine, so... yea, I've confirmed myself. It doesn't work on 1709 no matter how you got there (clean install, upgrade). Joy.

**Comment by BobVul** [comment]
Hopefully fixed by #15. I'll make a new release soon, probably tomorrow. Unfortunately, the install process has changed (read: gotten significantly more complex) - an actual installer is required to get the proper permissions to show toasts in 1709.

**Comment by BobVul** [comment]
@trentyarwood Could you please try the [2.0 release](https://github.com/BobVul/GrowlToToast/releases) and let me know how it goes?

**Comment by trentyarwood** [comment]
@BobVul there has been an unfortunate incident involving watercooler block coolant and **_all_** of the inside of my case.  when i have a new motherboard and video card, I will indeed and I'll let you know.

**Comment by BobVul** [comment]
Ouch! Sorry to hear that...
