### ISSUE TITLE
Create a proper installer

### ISSUE THREAD

**Issue by BobVul** [BobVul/GrowlToToast#15]
This will likely be a two-stage installation: an MSI installer to unpack the application into Program Files (along with a start menu shortcut to fix #11), and a custom application to find and install the Growler (Display) component into the Growl folders.

Unfortunately there is no good way to migrate existing installs.

**Comment by BobVul** [comment]
Another possibility is to have the MSI installer find and directly install into Growl folders, but that sounds risky - what if Growl is uninstalled without properly uninstalling GtT? We could leave orphan files behind...

**Comment by BobVul** [comment]
This is currently tracked in the wixinstaller branch. I have a working MSI installer now - just need to add the shortcut and figure out the second stage.

**Comment by MrsAngelD** [comment]
Hi, I was just wondering if any progress had been made on this? I miss this little thing so much more than I thought I would...lol.

**Comment by BobVul** [comment]
Ah... I got sidetracked some ways into it, sorry. I'll see what I can do, with a bit of luck maybe something working by tomorrow.

**Comment by BobVul** [comment]
@MrsAngelD [2.0 release](https://github.com/BobVul/GrowlToToast/releases) is out. Please try it and let me know if you have any issues.

**Comment by MrsAngelD** [comment]
@BobVul I do get notifications in the notification center, however persistence seems to be gone. Thank you!!

**Comment by BobVul** [comment]
Ah, yea, I noticed the persistence issue too. Not sure if/when I'll be able to fix it properly but there's a fairly simple workaround over in #19.
