### ISSUE TITLE
Showing images in notification

### ISSUE THREAD

**Issue by epichb** [BobVul/GrowlToToast#2]
Would it be possible to include Application images in the notifications like Visor or the default Notifications do it? This makes quickly identifying notification types a lot easier.

**Comment by BobVul** [comment]
Hm. That shouldn't be too difficult (hopefully!) but I'm going to have to come up with better communications rather than the current bodge with command line arguments.

**Comment by BobVul** [comment]
@epichb, this is now available in [v0.2a2](https://github.com/Elusive138/GrowlToToast/releases/tag/v0.2a2). Please let me know how it goes!

At the moment, I'm dumping these images into the temp folder. Might look into a way to avoid that later, but the Win10 Toast only takes URIs, not raw image data -- and a data URI is too long.

**Comment by epichb** [comment]
@Elusive138 works great.

You might want to think about scaling the images. As you can see in my attachment, the standard notification display scales the image to fit the quadratic frame. This is only an issue if the source application uses non-standard aspect ratios, so not strictly necessary if you assume to work with applications keeping to standard growl formats.

![toast vs standard](https://cloud.githubusercontent.com/assets/7453793/15946465/44fa246c-2e97-11e6-93ae-28534edddbdc.png)

**Comment by BobVul** [comment]
@epichb Sure, I'll take a look at that. I'll see if I can preserve the aspect ratio. Will also need to figure out what max size Windows allows.
