### ISSUE TITLE
Support non-English languages (Unicode)

### ISSUE THREAD

**Issue by Barbedx** [BobVul/GrowlToToast#24]
process.standardInput encoding problem - don't show cyrylic
Solution: 
StreamWriter utf8Writer = new StreamWriter(proc.StandardInput.BaseStream, new UTF8Encoding(false));--disable bom characters
utf8Writer.Write(...);
utf8Writer.Close();

**Comment by BobVul** [comment]
Can you give me a sample string in Cyrillic to test with?

**Comment by Barbedx** [comment]
Yes of course
"Привіт світ " Ukrainian
"Привет мир"  Russian
It don't work when pass it to standardImport and by Console.Readline.
Thanks.

Пн, 20 серп. 2018, 16:26 користувач Bob <notifications@github.com> пише:

**Comment by BobVul** [comment]
Cool, thanks. I'll take a look tomorrow, should be fairly simple. 

Alternatively it might give me an excuse to move to named pipes...

**Comment by BobVul** [comment]
Ok, not quite as simple as I'd hoped. There's a lot of iffiness around Windows codepages that make encoding changes for stdin/stdout difficult (e.g. I can easily use a custom encoding when writing to a redirected `StandardOutput` as you suggested, but I cannot easily change `Console.In`). The only solution would be calling into native code with P/Invoke... I'm reluctant to do that.

Instead, let's stop using unreliable stdin/stdout altogether and switch to anonymous pipes, which can be passed directly to a child process. Effectively, this should be solved by #9.

**Comment by BobVul** [comment]
![image](https://user-images.githubusercontent.com/1674237/44378924-de429780-a546-11e8-804a-97271ac40e6d.png)
![image](https://user-images.githubusercontent.com/1674237/44378946-fdd9c000-a546-11e8-86ce-5462e8523d94.png)

I will create a 2.0.3 release shortly.

**Comment by BobVul** [comment]
Please try https://github.com/BobVul/GrowlToToast/releases/tag/v2.0.3. Don't forget to run GrowlerInstaller after the main install so the Growl plugin is updated.

**Comment by Barbedx** [comment]
Great job, thank you very much!

**Comment by gimjun** [comment]
now it also shows emojis 💃 great job!
