### ISSUE TITLE
Notifications fail to display if linked icon is missing

### ISSUE THREAD

**Issue by jarnett** [BobVul/GrowlToToast#6]
I have some growl notifications that are generated using [GNTP Python Library](https://github.com/kfdm/gntp).  The link I had specified for the icon image was incorrect and this prevents the notifications from being displayed.

**Comment by BobVul** [comment]
Sorry it's taken me so long to get around to this

I'm hoping an incorrect link just means Growl gives me a null image, which #13 should fix.
