### ISSUE TITLE
font support

### ISSUE THREAD

**Issue by dellas60** [BobVul/GrowlToToast#8]
please to add other font support example arabic

**Comment by BobVul** [comment]
Could you give me a screenshot of how it currently appears? And some sample arabic text would be helpful too.

Also, which version of Windows 10 are you running? 1703? 1709? (I ask because I just discovered that this whole display might not work on 1709... hmm.)

**Comment by BobVul** [comment]
This might be fixed by #24. I'll close it for now, please reopen or create a new issue if it's not fixed. (I'm not sure about RTL support...)
