### ISSUE TITLE
More reliable message passing

### ISSUE THREAD

**Issue by BobVul** [BobVul/GrowlToToast#9]
Because Growl itself is .NET 2.0 (3.5) while Win10 Toasts require 4.0 (4.5/4.6), we need to send messages between the in-Growl DLL and the ex-Growl exe.

Unfortunately, the command line argument as in the original design is not long enough for some images, as in #2.

The stdin messaging introduced in #2 does not appear to be completely reliable, at least in 1709 in some cases.

Need to find a better way. Perhaps named pipes with a persistent Toaster?

**Comment by trentyarwood** [comment]
I've just reinstalled the new version, and can confirm that the latest version of [Android notifier](https://code.google.com/archive/p/android-notifier/downloads) works with Growl's other displays but not with GtT

Win10-64b 
v 1709
Build 16299.64

**Comment by BobVul** [comment]
Ah, damn... I'd been wondering if I was seeing things, thanks for the confirmation.

I'll look into it. The message passing seems to be a red herring - looks like it might be that funny requirement for apps that use notifications to have a start menu shortcut. Hm.

**Comment by BobVul** [comment]
Much easier to use anonymous pipes.
